<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Dota2GSI.Capture</RootNamespace>
    <AssemblyTitle>Dota2GSI Capture</AssemblyTitle>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dota2GSI\Dota2GSI.csproj" />
  </ItemGroup>

</Project>